### ISSUE TITLE
spacy ginza usage in Spyder with "AttributeError: module 'ginza' has no attribute 'Japanese'"

### ISSUE THREAD

**Issue by henyijen** [megagonlabs/ginza#104]
I am running Anaconda (2019-10) with Spyder 3 (IPython 7.12.0) in windows 10 environment and the python is 3.7.6.   Every time I am trying: 

import spacy
nlp=spacy.load('ja_ginza')

I have the following traceback message:
===============================
Traceback (most recent call last):

  File "<ipython-input-2-1cf5e9c589f5>", line 1, in <module>
    nlp=spacy.load('ja_ginza')

  File "C:\ana3\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 164, in load_model
    return load_model_from_package(name, **overrides)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 185, in load_model_from_package
    return cls.load(**overrides)

  File "C:\ana3\lib\site-packages\ja_ginza\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 196, in load_model_from_path
    cls = get_lang_class(lang)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 70, in get_lang_class
    if lang in registry.languages:

  File "C:\ana3\lib\site-packages\catalogue.py", line 56, in __contains__
    has_entry_point = self.entry_points and self.get_entry_point(name)

  File "C:\ana3\lib\site-packages\catalogue.py", line 140, in get_entry_point
    return entry_point.load()

  File "C:\ana3\lib\site-packages\importlib_metadata\__init__.py", line 94, in load
    module = import_module(match.group('module'))

  File "C:\ana3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "C:\Users\henyi\ginza.py", line 10, in <module>
    nlp = spacy.load('ja_ginza')

  File "C:\ana3\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 164, in load_model
    return load_model_from_package(name, **overrides)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 185, in load_model_from_package
    return cls.load(**overrides)

  File "C:\ana3\lib\site-packages\ja_ginza\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 196, in load_model_from_path
    cls = get_lang_class(lang)

  File "C:\ana3\lib\site-packages\spacy\util.py", line 70, in get_lang_class
    if lang in registry.languages:

  File "C:\ana3\lib\site-packages\catalogue.py", line 56, in __contains__
    has_entry_point = self.entry_points and self.get_entry_point(name)

  File "C:\ana3\lib\site-packages\catalogue.py", line 140, in get_entry_point
    return entry_point.load()

  File "C:\ana3\lib\site-packages\importlib_metadata\__init__.py", line 96, in load
    return functools.reduce(getattr, attrs, module)

AttributeError: module 'ginza' has no attribute 'Japanese' 
===================================

One interesting observation is that if I use python directly in windows 10's Powershell  with admin privilege, everything  goes  very well. But if not using admin privilege, I have the same traceback message shown in Spyder. Since I need the code-completion feature in Spyder, can you be of help? Thanks.

**Comment by henyijen** [comment]
It's me again. I found the problem now. Since I have created my own file also called ginza.py (same name with the module) and since the file is in the sys.path as indicated by IPython, thus the shadowing happens and it's the reason I got the AttributeError message as indicated above. So the solution to the above issue is very simple: DELETE my own GINZA.PY file.
