### ISSUE TITLE
Error Ginza when packaging application with pyinstaller 

### ISSUE THREAD

**Issue by hungnmai** [megagonlabs/ginza#161]
Traceback (most recent call last):
  File "ui/windows.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "ui/MaskingLayout.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "ai/masking/mask.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "ai/masking/csv_masking.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "ai/parser/example.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "ai/parser/extractor.py", line 7, in <module>
  File "spacy/__init__.py", line 30, in load
  File "spacy/util.py", line 170, in load_model
  File "spacy/util.py", line 191, in load_model_from_package
  File "ja_ginza/__init__.py", line 12, in load
  File "spacy/util.py", line 239, in load_model_from_init_py
  File "spacy/util.py", line 220, in load_model_from_path
  File "spacy/language.py", line 310, in create_pipe
KeyError: "[E002] Can't find factory for 'CompoundSplitter'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['CompoundSplitter']` or remove it from the model meta and add it via `nlp.add_pipe` instead."
[14858] Failed to execute script windows

**Comment by hiroshi-matsuda-rit** [comment]
Thank you for reporting the problem.
Actually, I'm not familiar with pyinstaller.
Could you tell me the reason why you prefer to use pyinstaller?
It seems there are some problems around the entry-points used in spaCy as the custom component registration framework.
https://github.com/megagonlabs/ginza/blob/develop/setup.py#L9

**Comment by acro5piano** [comment]
@hungnmai Have you found how to solve the problem?
