### ISSUE TITLE
”-s" option of command line does not work.

### ISSUE THREAD

**Issue by r-oguro** [megagonlabs/ginza#185]
Hi guys, I got error like below.
```
$ ginza -s A
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ginza5_p38/bin/ginza", line 8, in <module>
    sys.exit(main_ginza())
  File "/opt/anaconda3/envs/ginza5_p38/lib/python3.8/site-packages/ginza/command_line.py", line 483, in main_ginza
    plac.call(run_ginza)
  File "/opt/anaconda3/envs/ginza5_p38/lib/python3.8/site-packages/plac_core.py", line 427, in call
    cmd, result = parser.consume(arglist)
  File "/opt/anaconda3/envs/ginza5_p38/lib/python3.8/site-packages/plac_core.py", line 278, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/opt/anaconda3/envs/ginza5_p38/lib/python3.8/site-packages/ginza/command_line.py", line 467, in run_ginza
    run(
  File "/opt/anaconda3/envs/ginza5_p38/lib/python3.8/site-packages/ginza/command_line.py", line 79, in run
    analyzer.set_nlp()
  File "/opt/anaconda3/envs/ginza5_p38/lib/python3.8/site-packages/ginza/command_line.py", line 202, in set_nlp
    set_split_mode(nlp, self.split_mode)
  File "/opt/anaconda3/envs/ginza5_p38/lib/python3.8/site-packages/ginza/__init__.py", line 112, in set_split_mode
    splitter = nlp.get_pipe("CompoundSplitter")
  File "/opt/anaconda3/envs/ginza5_p38/lib/python3.8/site-packages/spacy/language.py", line 601, in get_pipe
    raise KeyError(Errors.E001.format(name=name, opts=self.component_names))
KeyError: "[E001] No component 'CompoundSplitter' found in pipeline. Available names: ['transformer', 'parser', 'attribute_ruler', 'ner', 'morphologizer', 'compound_splitter', 'bunsetu_recognizer']"
```
The old component name "CompoundSplitter" may be used somewhere.
Thank you.

```
$ pip list | grep -i ginza
ginza              5.0.1
ginza-transformers 0.3.1
ja-ginza           5.0.0
ja-ginza-electra   5.0.0
```

**Comment by hiroshi-matsuda-rit** [comment]
@r-oguro Thanks for reporting bugs. I fixed `set_split_mode()` and am going to release a bug-fix version.
