### ISSUE TITLE
[ERROR] "not found" message when specifying ja_ginza_electra

### ISSUE THREAD

**Issue by cidrugHug8** [megagonlabs/ginza#234]
Hi there,

When I executed the code below:
```
import spacy
nlp = spacy.load('ja_ginza_electra')
```
I got the following error and could not specify it. 
```
Cannot find the requested files in the cached path and outgoing traffic has been disabled. To enable model look-ups and downloads online, set 'local_files_only' to False.
trying to download model from huggingface hub: /tmp/tmpnvmt9ddh/config.json ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 568, in get_config_dict
    resolved_config_file = cached_path(
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 1776, in cached_path
    output_path = get_from_cache(
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 1994, in get_from_cache
    raise FileNotFoundError(
FileNotFoundError: Cannot find the requested files in the cached path and outgoing traffic has been disabled. To enable model look-ups and downloads online, set 'local_files_only' to False.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ginza_transformers/layers/hf_shim_custom.py", line 127, in from_bytes
    transformer = AutoModel.from_pretrained(config._name_or_path, local_files_only=True)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 418, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 582, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 593, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for '/tmp/tmpnvmt9ddh/config.json'. Make sure that:

- '/tmp/tmpnvmt9ddh/config.json' is a correct model identifier listed on 'https://huggingface.co/models'
  (make sure '/tmp/tmpnvmt9ddh/config.json' is not a path to a local directory with something else, in that case)

- or '/tmp/tmpnvmt9ddh/config.json' is the correct path to a directory containing a config.json file
```
Can you please tell me how to solve this problem?

**Comment by tnakae** [comment]
@cidrugHug8
I got the same error as you reported above.
These are library versions I used:

```
ginza==5.1.0
ja-ginza-electra==5.1.0
spacy-transformers==1.1.4
transformers==4.15.0
```

I suspect that this error is due to specification change of transformers.
When I downgraded `transformers==4.12.5` and executed `spacy.load('ja_ginza_electra')`, there was no error.
I think `4.12.5` is boundary condition because `transformers==4.13.0` generated the same error.

**Comment by hiroshi-matsuda-rit** [comment]
Hi @cidrugHug8 and @tnakae,
Thank you for reporting this issue.
We've deployed revised version of ginza-transformers (0.4.1) which restricts transformers <= 4.13.0.
Could you please test it via `pip install -U` ?
```console
$ pip install -U ja-ginza-electra ginza-transformers transformers
```

**Comment by tnakae** [comment]
@hiroshi-matsuda-rit 
Nice job!
When I updated packages, no error occurred. Thanks!
