### ISSUE TITLE
TypeError: create_lemmatizer() got an unexpected keyword argument 'lookups'

### ISSUE THREAD

**Issue by pigooosuke** [megagonlabs/ginza#51]
I installed ginza.

```
pip3 install "https://github.com/megagonlabs/ginza/releases/download/latest/ginza-latest.tar.gz"
~~~
Successfully installed SudachiDict-core-20190531 SudachiPy-0.4.0 blis-0.4.1 cymem-2.0.2 dartsclone-0.6 ginza-2.0.0 ja-ginza-2.1.0 murmurhash-1.0.2 plac-0.9.6 preshed-3.0.2 sortedcontainers-2.1.0 spacy-2.2.0 srsly-0.1.0 thinc-7.1.1 wasabi-0.2.2
```

pip 19.1.1

But, 
```
$ginza
Traceback (most recent call last):
  File "/usr/local/bin/ginza", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ginza/command_line.py", line 130, in main
    plac.call(run)
  File "/usr/local/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ginza/command_line.py", line 36, in run
    nlp = spacy.load('ja_ginza')
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 166, in load_model
    return load_model_from_package(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 187, in load_model_from_package
    return cls.load(**overrides)
  File "/usr/local/lib/python3.7/site-packages/ja_ginza/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 199, in load_model_from_path
    nlp = cls(meta=meta, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 181, in __init__
    vocab = factory(self, **meta.get("vocab", {}))
  File "/usr/local/lib/python3.7/site-packages/spacy/language.py", line 63, in create_vocab
    lemmatizer = cls.create_lemmatizer(nlp, lookups=lookups)
TypeError: create_lemmatizer() got an unexpected keyword argument 'lookups'
```

How can I fix error?

**Comment by hiroshi-matsuda-rit** [comment]
@pigooosuke The spaCy's API has been changed in v.2.2 released yesterday. I've already solved this error by adding an argument to create_lemmatizer() but It takes a while to release the new version of GiNZA because the model training takes about two days. Please down-grade spaCy to v2.1.8 by `pip install -U spacy==2.1.8`.

**Comment by pigooosuke** [comment]
Thank you for the quick reply.
I'm looking forward to it!
