### ISSUE TITLE
ImportError: Japanese support requires SudachiPy distributed with ja language model

### ISSUE THREAD

**Issue by learnercat** [megagonlabs/ginza#71]
I installed Ginza into Docker-Ubuntu-Latest and Python 3.6.9 environment as following:
`pip install "https://github.com/megagonlabs/ginza/releases/download/latest/ginza-latest.tar.gz"`
I tried to install and uninstall again and again but it didn't work.

`>>> import spacy`
`>>> nlp = spacy.load('ja_ginza')`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ginza/sudachi_tokenizer.py", line 34, in try_import_sudachipy_dictionary
    from sudachipy import dictionary
ImportError: cannot import name 'dictionary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 164, in load_model
    return load_model_from_package(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 185, in load_model_from_package
    return cls.load(**overrides)
  File "/usr/local/lib/python3.6/dist-packages/ja_ginza/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 197, in load_model_from_path
    nlp = cls(meta=meta, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 173, in __init__
    make_doc = factory(self, **meta.get("tokenizer", {}))
  File "/usr/local/lib/python3.6/dist-packages/ginza/__init__.py", line 49, in create_tokenizer
    return SudachiTokenizer(nlp)
  File "/usr/local/lib/python3.6/dist-packages/ginza/sudachi_tokenizer.py", line 62, in __init__
    dictionary = try_import_sudachipy_dictionary()
  File "/usr/local/lib/python3.6/dist-packages/ginza/sudachi_tokenizer.py", line 38, in try_import_sudachipy_dictionary
    "Japanese support requires SudachiPy distributed with ja language model"
ImportError: Japanese support requires SudachiPy distributed with ja language model`

Please help me how can I fix these errors.

**Comment by hiroshi-matsuda-rit** [comment]
@learnercat Thank you for reporting. The SudachiPy was just updated as referring the dictionary file in different way which the current version of GiNZA expects. I'd like to release a quick fix for this issue ASAP. Please wait.

**Comment by hiroshi-matsuda-rit** [comment]
@learnercat I tested the latest version of GiNZA on Python 3.6.9 with Ubuntu 19.04 but no problem found. The error message which you got might be related with missing the SudachiPy package.
Would you paste the output of `pip list` here?
Or please try to install SudachiPy and its dictionary after installing GiNZA.

**Comment by learnercat** [comment]
Thank you very much. I have run this command line:
`pip3 install https://object-storage.tyo2.conoha.io/v1/nc_2520839e1f9641b08211a5c85243124a/sudachi/SudachiDict_core-20191030.tar.gz
`
Now it works properly.
