### ISSUE TITLE
[pipenv] Can't load system.dic

### ISSUE THREAD

**Issue by fortharrow** [megagonlabs/ginza#81]
I installed ginza on pipenv environment but they couldn't work well.

Error message said that
ValueError: cannot mmap an empty file
And when I check up the file "system.dic", the file is empty text file.

I assumed that that was something like symbolic link or so, but I don't know what.

I tried to install ja_ginza independently but it happened again.
It would be great if you could let me know how to fix it.

Below is the message for the error :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\spacy\util.py", line 164, in load_model
    return load_model_from_package(name, **overrides)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\spacy\util.py", line 185, in load_model_from_package
    return cls.load(**overrides)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\ja_ginza\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\spacy\util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\spacy\util.py", line 197, in load_model_from_path
    nlp = cls(meta=meta, **overrides)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\spacy\language.py", line 173, in __init__
    make_doc = factory(self, **meta.get("tokenizer", {}))
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\ginza\__init__.py", line 50, in create_tokenizer
    return SudachipyTokenizer(nlp)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\ginza\sudachipy_tokenizer.py", line 81, in __init__
    dict_ = dictionary.Dictionary(config_path=config_path)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\sudachipy\dictionary.py", line 37, in __init__
    self._read_system_dictionary(config.settings.system_dict_path())
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\sudachipy\dictionary.py", line 66, in _read_system_dictionary
    dict_ = BinaryDictionary.from_system_dictionary(filename)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\sudachipy\dictionarylib\binarydictionary.py", line 51, in from_system_dictionary
    args = cls._read_dictionary(filename)
  File "C:\Users\191805\.virtualenvs\myenv-VXX64T0S\lib\site-packages\sudachipy\dictionarylib\binarydictionary.py", line 35, in _read_dictionary
    bytes_ = mmap.mmap(system_dic.fileno(), 0, access=access)
ValueError: cannot mmap an empty file

**Comment by hiroshi-matsuda-rit** [comment]
@fortharrow Thank you for reporting the problem related to pipenv. I'd try to solve the cause of the dictionary install error.
The empty system.dic which you saw in ja_ginza/sudachidict/ should be overwritten while executing ja_ginza/setup.py by pip, but actually not by pipenv.
If you need a quick fix, please download and extract a zip archive below, then overwrite empty system.dic with zip content.
https://github.com/megagonlabs/ginza/releases/download/v3.0.0/SudachiDict_core-20191224.zip

There are many python package management environments and it's hard to test all of them for us, hence your error report is very useful to improve

**Comment by fortharrow** [comment]
Thank you for your quick response. Will try it.

**Comment by hiroshi-matsuda-rit** [comment]
@fortharrow I just released GiNZA v3.1.0 with some implementation improvements around sudachidict distribution. Please try it and feedback the errors if you found.
```
$ pip install -U ginza
```
